spring.application.name=api

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/cinetech
spring.datasource.username=postgres
spring.datasource.password=romero13
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração do servidor
server.port=8080

# Configuração de inicialização do banco
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8

# Desabilitar DevTools LiveReload e restart automático
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false